@startuml

title Remote client - Class Diagram

interface IRemoteServerAPI {
    +client_connected()
    +mq_open()
    +mq_open_with_params()
    +mq_close()
    +mq_unlink()
    +mq_send()
    +mq_receive()
    +mq_clear()
    +shm_open()
    +shm_close()
    +app_start()
    +app_stop()
    +app_check_status()
    +file_backup()
    +file_restore()
    +file_update()
    +file_exists()
    +file_delete()
    +file_content()
    +folder_exists()
    +folder_delete()
    +folder_create()
    +command_execute()
}

class RpcClient {
}

class SDLRemoteTestAdapterClient {
    +connected()
    +open(string)
    +open_with_params(string, int, int, int, int)
    +send(string, string)
    +receive(string)
    +close(string)
    +unlink(string)
    +clear()
    +shm_open(string, int)
    +shm_close(string)
    +app_start(string, string)
    +app_stop(string)
    +app_check_status(string)
    +file_exists(string, string)
    +file_update(string, string, string)
    +file_content(string, string)
    +file_delete(string, string)
    +file_backup(string, string)
    +file_restore(string, string)
    +folder_exists(string)
    +folder_create(string)
    +folder_delete(string)
    +command_execute(string)
}

class SDLRemoteTestAdapterQtClient {
    +SDLRemoteTestAdapterQtClient(SDLRemoteTestAdapterClient, MqParams, MqParams, vector<ShmParams>, QObject)
    +~SDLRemoteTestAdapterQtClient()
    +connectMq()
    +send(string)
    +receive()
    --signals--
    +textMessageReceived(string)
    +bytesWritten(int)
    +connected()
    +disconnected()
    --
    -connectionLost()
}

class SDLRemoteTestAdapterReceiveThread {
    +SDLRemoteTestAdapterReceiveThread(SDLRemoteTestAdapterQtClient, QObject)
    +~SDLRemoteTestAdapterReceiveThread()
    -run()
}

class QThread

interface ISDLRemoteTestAdapter {
    +connect(SDLRemoteTestAdapterQtClient)
    +write(SDLRemoteTestAdapterQtClient, string)
}

class SDLRemoteTestAdapterLuaWrapper {
    +SDLRemoteTestAdapterLuaWrapper(SDLRemoteTestAdapterClient, MqParams, MqParams, vector<ShmParams>)
}

interface ISDLRemoteClient {
    +connected(SDLRemoteTestAdapterClient)
    +open(SDLRemoteTestAdapterClient, string)
    +open_with_params(SDLRemoteTestAdapterClient, string, int, int, int, int)
    +send(SDLRemoteTestAdapterClient, string, string)
    +receive(SDLRemoteTestAdapterClient, string)
    +close(SDLRemoteTestAdapterClient, string)
    +unlink(SDLRemoteTestAdapterClient, string)
    +clear(SDLRemoteTestAdapterClient)
    +app_start(SDLRemoteTestAdapterClient, string, string)
    +app_stop(SDLRemoteTestAdapterClient, string)
    +app_check_status(SDLRemoteTestAdapterClient, string)
    +command_execute(SDLRemoteTestAdapterClient, string)
    +file_exists(SDLRemoteTestAdapterClient, string, string)
    +file_update(SDLRemoteTestAdapterClient, string, string, string)
    +file_content(SDLRemoteTestAdapterClient, string, string)
    +file_delete(SDLRemoteTestAdapterClient, string, string)
    +file_backup(SDLRemoteTestAdapterClient, string, string)
    +file_restore(SDLRemoteTestAdapterClient, string, string)
    +folder_exists(SDLRemoteTestAdapterClient, string)
    +folder_create(SDLRemoteTestAdapterClient, string)
    +folder_delete(SDLRemoteTestAdapterClient, string)
}

class SDLRemoteClientLuaWrapper {
    +SDLRemoteClientLuaWrapper(string, int)
}

SDLRemoteTestAdapterClient *-- RpcClient
SDLRemoteTestAdapterClient -- IRemoteServerAPI

SDLRemoteTestAdapterQtClient o-- SDLRemoteTestAdapterClient

QThread <|-- SDLRemoteTestAdapterReceiveThread

ISDLRemoteClient <|-- SDLRemoteClientLuaWrapper
SDLRemoteClientLuaWrapper o-- SDLRemoteTestAdapterClient

ISDLRemoteTestAdapter <|-- SDLRemoteTestAdapterLuaWrapper
SDLRemoteTestAdapterLuaWrapper o-- SDLRemoteTestAdapterQtClient
SDLRemoteTestAdapterQtClient *-- SDLRemoteTestAdapterReceiveThread

note "All methods are executing synchronous (blocking)" as N
SDLRemoteTestAdapterQtClient .. N

@enduml
